### ISSUE TITLE
String format specifier

### ISSUE THREAD

**Issue by ghost** [andyshep/Palettes#3]
Hi,

In CachingIncrementalStore.swift: what does %K string format specifier mean here?

```swift
let predicate = NSPredicate(format: "%K = %@", kPALResourceIdentifierAttributeName, refObj.description)
```

I can't find a mention of it in [Apple's doc's](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html).

**Comment by andyshep** [comment]
The `%K` format specifier is used with `NSPredicate` and represents a key path. In this case, `%K` will be substituted for the attribute name key path. 

You can find more information in the [Predicate Programming Guide](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html).

**Comment by ghost** [comment]
Thanks
